### ISSUE TITLE
installation process

### ISSUE THREAD

**Issue by Sijbrandb** [moflaher/ttide_py#27]
Hi,
I am trying to install ttide for python, however when running $ python setup.py install, i get a SyntaxError. 

Same goes for: 

"from setuptools import setup

def readme():
    with open('README.md') as f:
        return f.read()

setup(name='ttide',
      version='0.3_exp',
      description='Python distribution of the MatLab package TTide.',
      long_description=readme(),
      url='https://github.com/moflaher/ttide_py',
      author='Mitchell O\'Flaherty-Sproul',
      author_email='073208o@acadiau.ca',
      license='MIT',
      packages=['ttide'],
      package_data={'ttide': ['data/*.nc']},
      zip_safe=False)" 
It would be great if someone can help me out with the installation process!

Kind regards,
Sijbrand

**Comment by mdunphy** [comment]
Try `pip install .` from the repo directory

**Comment by mdunphy** [comment]
What is the error? 

You may need to add `--user`

**Comment by Sijbrandb** [comment]
Cell In [4], line 1
    python setup.py install
           ^
SyntaxError: invalid syntax

**Comment by mdunphy** [comment]
Looks like you're running that command from inside a python interpreter. The install should run from command line
