### ISSUE TITLE
Issue with complex input to t_tide

### ISSUE THREAD

**Issue by annks** [moflaher/ttide_py#3]
Hi,

It is great to have a t_tide package working for python! 

I am using it to perfom harmonic analysis on time series of currents, thus submitting a complex vector to t_tide.  The returned tidecon contains only 4 values, not 8 as expected. 
I create a complex `xin` from vectors (numpy arrays) `u`and `v`
```
xin =u + v*1j
xin.dtype
dtype('complex64')
```
Inside `t_tide`, there are several tests of the form `if (xin.dtype!=complex)`. These fail when `dtype('complex64')`, even though `xin` indeed is complex. 
I went ahead and changed all these tests with `if (not 'complex' in xin.dtype.name):`  which makes the test independent of bit size.
 
With this change the code now works as expected, perhaps you could consider changing the  code accordingly?

**Comment by moflaher** [comment]
Done. Thanks for the suggestion!
I had been unsure of the best way to resolve this in the past.

I've pushed the changes to the experimental branch.
