### ISSUE TITLE
Running ttide_py with four arguments

### ISSUE THREAD

**Issue by shahidul001** [moflaher/ttide_py#4]
Hi : I am trying to run the t_tide with four arguments instead of default one argument (ie, just time series datasets). I have received  the following error message:
*** AttributeError: 'NoneType' object has no attribute 'datestr2num'

here is the main code:
data=np.genfromtxt('Model_predicted_WSE.txt', delimiter='')
XIN=data;
obs_data1=np.genfromtxt('Observed_WSE.txt', delimiter='')
data_length=len(obs_data1)
counter=np.arange(0,data_length,10)
obs_data=obs_data1[counter]
INTERVAL=1.0; # interval in hours
date1 = datetime.datetime(2015,8,13,0,0,0);
START_TIME=matplotlib.dates.date2num(date1)
LATITUDE=-77.08281;
RAYLEIGH=1.0
[name, freq, tidecon, xout]=t_tide(XIN,dt=1,stime=START_TIME,lat=LATITUDE);

**Comment by shahidul001** [comment]
I appreciate somebody's help in solving this error.

**Comment by moflaher** [comment]
Can I get the full error output?

**Comment by shahidul001** [comment]
Thank you so  much for your kind reply. it is working now. Previously, I
made a mistake in converting time unit conversion. by the way, do you know
what is the time datum? GMT or local time?

Thank you for your help.

Regards
Shahidul

**Comment by moflaher** [comment]
No problem I'm glad you got it working.
The time datum is GMT.

Please don't hesitate to ask for help if you have any additional issues.

Mitchell

**Comment by shahidul001** [comment]
By the way, I receive the following warning. What does it signify?

C:\Anaconda\lib\site-packages\ttide-0.3_exp-py2.7.egg\ttide\t_vuf.py:57:
FutureWarning: comparison to `None` will result in an elementwise object
comparison in the future.
  if lat != None:
-----------------------------------
Thanks
Shahidul

**Comment by shahidul001** [comment]
Thank you for your prompt reply. I appreciate it.

Regards
Shahidul

**Comment by moflaher** [comment]
That FutureWarning is from newer versions of numpy when using *var==None*.  It can be fixed with the more Idiomatic *var is None*.

Not a problem, enjoy the module!
