### ISSUE TITLE
Adding constituents with shallownames

### ISSUE THREAD

**Issue by RCand** [moflaher/ttide_py#5]
Hello,
I have a problem while trying to add constituents with shallownames. 
I need to add the constituent M10. 

In eta I have the record of the elevations.

    nameu, fu, tideconout, pout = t_tide(xin=eta, stime=t, shallownames=['M10 '])
                                             
This is the output:

C:\Anaconda3\python.exe C:/Users/hp1/Desktop/ex_folder/exemple.py
C:\Users\hp1\Desktop\ex_folder\t_vuf.py:57: FutureWarning: comparison to `None` will result in an elementwise object comparison in the future.
    if lat != None:

-----------------------------------
nobs = 4201 
ngood = 4201 
record length (days) = 175.04
start time: 1997-04-03 00:00:00
rayleigh criterion = 1.0

Greenwich phase computed with nodal corrections 
 applied to amplitude and phase relative to center time

x0= -0.106, x trend= 0
var(x)=  4197.5431715804625    var(xp)=  3704.2374706582254    var(xres)=  272.2808579938627 

percent var predicted/var original= 88.2 

 tidal amplitude and phase with 95 % CI estimates
 
tide      freq        amp      amp_err    pha      pha_err    snr
  MM    0.0015122     6.2492     7.602    121.38     66.12      0.68
* MSF   0.0028219    11.5526     6.571    330.42     32.23       3.1
  ALP1  0.0343966     0.5276     1.072    127.62    135.20      0.24
  2Q1   0.0357064     0.2322     1.057     59.44    190.61     0.048
* Q1    0.0372185     1.9127     1.228    305.60     41.09       2.4
* O1    0.0387307     6.4743     1.363    107.30     14.04        23
  NO1   0.0402686     0.4263     0.806    131.94    128.48      0.28
* K1    0.0417807     9.3023     1.310    120.82      7.92        50
  J1    0.0432929     0.8867     1.394    340.64     91.08       0.4
  OO1   0.0448308     0.1992     1.375     25.28    234.31     0.021
  UPS1  0.0463430     0.3619     1.324    282.68    217.00     0.075
  EPS2  0.0761773     2.1324     1.781    337.10     60.63       1.4
* MU2   0.0776895     6.4384     2.009     91.13     15.90        10
* N2    0.0789992    13.9743     1.903    128.77      7.83        54
* M2    0.0805114    79.6145     1.878    246.97      1.37   1.8e+03
* L2    0.0820236     8.5062     2.322      4.36     13.76        13
* S2    0.0833333    18.8886     2.221    202.12      5.79        72
  ETA2  0.0850736     0.9417     2.544    303.72    159.28      0.14
* MO3   0.1192421     1.7221     0.427    222.73     15.10        16
* M3    0.1207671     0.4273     0.278    329.73     47.07       2.4
* MK3   0.1222921     1.4538     0.360    256.38     15.76        16
  SK3   0.1251141     0.3815     0.417     83.66     64.54      0.84
* MN4   0.1595106     2.9281     0.455    297.73      9.62        41
* M4    0.1610228     5.9875     0.504     54.59      4.51   1.4e+02
  SN4   0.1623326     0.4116     0.495    292.67     67.27      0.69
* MS4   0.1638447     3.2917     0.550     13.58      9.66        36
* S4    0.1666667     1.0015     0.581    350.40     28.75         3
* 2MK5  0.2028035     0.9837     0.349    309.05     19.83       7.9
  2SK5  0.2084474     0.2805     0.310    336.68     75.18      0.82
* 2MN6  0.2400221     2.4407     0.643    316.27     15.10        14
* M6    0.2415342     4.2881     0.675     74.33      8.01        40
* 2MS6  0.2443561     3.9974     0.686     25.57      9.72        34
  2SM6  0.2471781     0.8030     0.679      4.65     53.49       1.4
* 3MK7  0.2833149     0.5167     0.213     52.58     24.68       5.9
* M8    0.3220456     1.0046     0.144    225.15      9.27        48

Thanks

**Comment by moflaher** [comment]
The shallow code has not been finished yet. If you want to fix it I will accept a pull request for it.
Otherwise it will probably be a week or two before I get a chance to look at it.

Mitchell

**Comment by moflaher** [comment]
This should be fixed in the shallowfix branch. 
Can you pull it, run it, and confirm that it is working as you might expect?

Thanks!

**Comment by RCand** [comment]
Yes it is working properly! 
Thank you very much.
