### ISSUE TITLE
Start Date

### ISSUE THREAD

**Issue by peteretep** [moflaher/ttide_py#8]
I'm not clear how to specify start date for t_tide:

    [nameu, freq, tidecon, xout] = t_tide(elevation, lat=54.38833, stime=[2011,12,7,13,45,0],  interval=0.25)
Gives 
    
    *** ValueError: setting an array element with a sequence.

What format should the value for stime be in?
Thanks.

**Comment by moflaher** [comment]
stime takes a datenum. I like to use matplotlib.dates.

Try,
import matplotlib.dates as dates
mystime = dates.datestr2num('2011-12-7 13:45:0')
[nameu, freq, tidecon, xout] = t_tide(elevation, lat=54.38833, stime=mystime,  interval=0.25)

Let me know if that does not work for you.

**Comment by peteretep** [comment]
thanks
